/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import org.junit.jupiter.api.Test;

import java.io.*;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class AppTest {

    @Test
    void ShouldWinIfAllNonMinesAreOpened() throws IOException {

        BufferedReader reader = mock(BufferedReader.class);
        Random random = mock(Random.class);

        when(reader.readLine()).thenReturn("3")    // Size of the grid
                .thenReturn("1")                   // Number of mines
                .thenReturn("A1")
                .thenReturn("A2")
                .thenReturn("A3")
                .thenReturn("B1")
                .thenReturn("B3")
                .thenReturn("C1")
                .thenReturn("C2")
                .thenReturn("C3")
                .thenReturn("Q");

        when(random.nextInt(anyInt())).thenReturn(1);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(out));

        App.play(reader, random);

        String output = out.toString();

        assertTrue(output.contains("Congratulations, you have won the game!"));

        System.setOut(originalOut);
    }

    @Test
    void ShouldLoseIfMineCellIsOpened() throws IOException {

        BufferedReader reader = mock(BufferedReader.class);
        Random random = mock(Random.class);

        when(reader.readLine()).thenReturn("3")    // Size of the grid
                .thenReturn("1")                   // Number of mines
                .thenReturn("B2")
                .thenReturn("Q");

        when(random.nextInt(anyInt())).thenReturn(1);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(out));

        App.play(reader, random);

        String output = out.toString();

        assertTrue(output.contains("Oh no, you detonated a mine! Game over."));

        System.setOut(originalOut);
    }

}
